import { NextRequest, NextResponse } from 'next/server';
import type { GenerationResult } from '@/types';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { variations, projectName } = body as {
      variations: GenerationResult[];
      projectName?: string;
    };

    if (!variations || variations.length === 0) {
      return NextResponse.json(
        { error: 'No variations to download' },
        { status: 400 }
      );
    }

    // For single variation, just return the HTML directly
    if (variations.length === 1) {
      const html = variations[0].html;
      const fileName = projectName
        ? `${projectName.replace(/[^a-z0-9]/gi, '-')}.html`
        : 'landing-page.html';

      return new NextResponse(html, {
        headers: {
          'Content-Type': 'text/html',
          'Content-Disposition': `attachment; filename="${fileName}"`,
        },
      });
    }

    // For multiple variations, create a simple combined response
    // Build a simple HTML with all variations
    const combinedHtml = `<!DOCTYPE html>
<html>
<head>
  <title>${projectName || 'Landing Page Variations'}</title>
  <style>
    body { font-family: system-ui, sans-serif; padding: 20px; }
    .variation { margin: 20px 0; padding: 20px; border: 1px solid #ddd; border-radius: 8px; }
    .variation h2 { margin-top: 0; }
    .download-btn { background: #6366f1; color: white; padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer; }
    iframe { width: 100%; height: 600px; border: 1px solid #ccc; }
  </style>
</head>
<body>
  <h1>${projectName || 'Generated Landing Pages'}</h1>
  <p>Generated by Adhoq Landing Page Builder</p>

  ${variations.map((v, i) => `
  <div class="variation">
    <h2>Variation ${i + 1}</h2>
    <p>Changes: ${v.changes.length}</p>
    <button class="download-btn" onclick="downloadVariation(${i})">Download HTML</button>
  </div>
  `).join('')}

  <script>
    const variations = ${JSON.stringify(variations.map(v => v.html))};
    function downloadVariation(index) {
      const html = variations[index];
      const blob = new Blob([html], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = 'variation-' + (index + 1) + '.html';
      a.click();
      URL.revokeObjectURL(url);
    }
  </script>
</body>
</html>`;

    return new NextResponse(combinedHtml, {
      headers: {
        'Content-Type': 'text/html',
        'Content-Disposition': `attachment; filename="${projectName || 'variations'}.html"`,
      },
    });
  } catch (error) {
    console.error('Download error:', error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to create download' },
      { status: 500 }
    );
  }
}
